orangecontrib/survival_analysis/widgets/__init__.py, orangecontrib/survival_analysis/widgets/owkaplanmeier.py, orangecontrib/survival_analysis/widgets/tests/test_owkaplanmeier.py
https://github.com/biolab/genialis/issues/4
=> [NEW] Add kaplan-meier widget

orangecontrib/survival_analysis/widgets/owkaplanmeier.py
=> [FIX] owkaplanmeier: fix median survival time

.coveragerc, .github/workflows/test.yml, setup.cfg, tox.ini
https://github.com/biolab/orange3/issues/5145
Replace travis with GH actions and add tox configuration.
=> maintenance, tox, github actions

orangecontrib/survival_analysis/widgets/owkaplanmeier.py, orangecontrib/survival_analysis/widgets/tests/test_owkaplanmeier.py
=> add more tests for kaplan-meier widget and fix median survival time

orangecontrib/survival_analysis/widgets/owkaplanmeier.py
```
Traceback (most recent call last):
File "/Users/jakakokosar/.pyenv/versions/orange/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
handler(*args)
File "/Users/jakakokosar/Documents/dev/orange/orange3-survival-analysis/orangecontrib/survival_analysis/widgets/owkaplanmeier.py", line 443, in set_data
self.graph.curves = {curve_id: curve for curve_id, curve in enumerate(self.generate_plot_curves())}
File "/Users/jakakokosar/Documents/dev/orange/orange3-survival-analysis/orangecontrib/survival_analysis/widgets/owkaplanmeier.py", line 495, in generate_plot_curves
return [EstimatedFunctionCurve(time, events)]
File "/Users/jakakokosar/Documents/dev/orange/orange3-survival-analysis/orangecontrib/survival_analysis/widgets/owkaplanmeier …
```
=> [FIX] owkaplanmeier: handle missing values

orangecontrib/survival_analysis/widgets/owkaplanmeier.py
The previous solution did not work when dealing with meta attributes.
=> [FIX] owkaplanmeier: fix missing values handling

orangecontrib/survival_analysis/widgets/owkaplanmeier.py, orangecontrib/survival_analysis/widgets/tests/test_owkaplanmeier.py
Add more info to the plot legend
=> [ENH] owkaplanmeier: add more information to the plot legend

orangecontrib/survival_analysis/widgets/owkaplanmeier.py
=> [ENH] owkaplanmeier: add log-rank to legend footer, change context handler

orangecontrib/survival_analysis/widgets/owstepwisecoxregression.py
=> [ENH] add Stepwise Cox Regression widget

orangecontrib/survival_analysis/widgets/owkaplanmeier.py
=> [FIX] owkaplanmeier: hide legend on empty input

orangecontrib/survival_analysis/evaluation/scoring.py, orangecontrib/survival_analysis/modeling/cox.py, orangecontrib/survival_analysis/widgets/data.py, orangecontrib/survival_analysis/widgets/owassurvivaldata.py, orangecontrib/survival_analysis/widgets/owcoxregression.py, orangecontrib/survival_analysis/widgets/owkaplanmeier.py, orangecontrib/survival_analysis/widgets/owranksurvivalfeatures.py, orangecontrib/survival_analysis/widgets/owstepwisecoxregression.py, orangecontrib/survival_analysis/widgets/tests/datasets/README.txt, orangecontrib/survival_analysis/widgets/tests/datasets/toy_example.tab, orangecontrib/survival_analysis/widgets/tests/test_owassurvivaldata.py, orangecontrib/survival_analysis/widgets/tests/test_owkaplanmeier.py, setup.cfg, tox.ini
=> [ENH] Survival tables, CoxRegression model and learner

orangecontrib/survival_analysis/modeling/cox.py, orangecontrib/survival_analysis/widgets/owranksurvivalfeatures.py, orangecontrib/survival_analysis/widgets/owstepwisecoxregression.py
=> [FIX] Various bug fixes and improvements

orangecontrib/survival_analysis/modeling/cox.py, orangecontrib/survival_analysis/widgets/data.py, orangecontrib/survival_analysis/widgets/owkaplanmeier.py, orangecontrib/survival_analysis/widgets/tests/datasets/toy_example.tab, orangecontrib/survival_analysis/widgets/tests/test_owkaplanmeier.py
=> [ENH] Detect and omit missing rows

orangecontrib/survival_analysis/widgets/owchorts.py
=> [ENH] owcohorts: add new widget

orangecontrib/survival_analysis/widgets/owassurvivaldata.py, orangecontrib/survival_analysis/widgets/owkaplanmeier.py, orangecontrib/survival_analysis/widgets/tests/test_owassurvivaldata.py
=> [ENH] Set valid types for survival and group variables in DomainModel

orangecontrib/survival_analysis/__init__.py, orangecontrib/survival_analysis/evaluation/__init__.py, orangecontrib/survival_analysis/evaluation/scoring.py, orangecontrib/survival_analysis/modeling/cox.py, orangecontrib/survival_analysis/widgets/data.py, orangecontrib/survival_analysis/widgets/owassurvivaldata.py, orangecontrib/survival_analysis/widgets/owchorts.py, orangecontrib/survival_analysis/widgets/owkaplanmeier.py, orangecontrib/survival_analysis/widgets/owranksurvivalfeatures.py, orangecontrib/survival_analysis/widgets/owstepwisecoxregression.py, orangecontrib/survival_analysis/widgets/tests/test_owassurvivaldata.py, orangecontrib/survival_analysis/widgets/tests/test_owkaplanmeier.py, setup.cfg, tox.ini
=> [ENH] move survival annotations to attributes of columns

orangecontrib/survival_analysis/widgets/owassurvivaldata.py
=> [FIX] owassurvivaldata: fix variable selection on widget startup

orangecontrib/survival_analysis/widgets/owkaplanmeier.py, orangecontrib/survival_analysis/widgets/owranksurvivalfeatures.py
Changes:
- Set auto commit to True by default.
- Sort rows by p-values on ranking finished. 
- set widget size hints
=> [ENH] owranksurvivalfeatures: minor UI improvements

orangecontrib/survival_analysis/widgets/owstepwisecoxregression.py
Changes:
- set auto commit button to True by default
- use more general x-axis label
=> [ENH] owstepwisecoxregression: minor UI changes

orangecontrib/survival_analysis/widgets/owkaplanmeier.py
If available, autoselect 'Cohort' variable from the input domain as a group indicator.
=> [ENH] owkaplanmeier: If input domain contains variable 'Cohorts' autoselect it

orangecontrib/survival_analysis/modeling/cox.py, orangecontrib/survival_analysis/widgets/owranksurvivalfeatures.py, orangecontrib/survival_analysis/widgets/owstepwisecoxregression.py, orangecontrib/survival_analysis/widgets/tests/datasets/toy_example.tab
=> [ENH] Simplify conversion of Table to DataFrame

orangecontrib/survival_analysis/evaluation/scoring.py, orangecontrib/survival_analysis/modeling/cox.py, orangecontrib/survival_analysis/widgets/data.py, orangecontrib/survival_analysis/widgets/owcoxregression.py
https://github.com/biolab/orange3/pull/5848
=> [ENH] use new interface for testing and scoring learners

orangecontrib/survival_analysis/modeling/cox.py, orangecontrib/survival_analysis/widgets/owchorts.py
=> [FIX] owcohorts: transform domain before computing

doc/widgets.json, orangecontrib/survival_analysis/widgets/owassurvivaldata.py, orangecontrib/survival_analysis/widgets/owchorts.py, orangecontrib/survival_analysis/widgets/owcoxregression.py, orangecontrib/survival_analysis/widgets/owkaplanmeier.py, orangecontrib/survival_analysis/widgets/owranksurvivalfeatures.py, orangecontrib/survival_analysis/widgets/owstepwisecoxregression.py
=> [ENH] Prepare widget catalogue

orangecontrib/survival_analysis/modeling/cox.py, orangecontrib/survival_analysis/widgets/owcoxregression.py
Widget now outputs additional statistics (as is implemented in lifelines).
=> [ENH] owcoxregression: output additional statistics

orangecontrib/survival_analysis/widgets/owchorts.py
=> [ENH] owcohors: add model and coefficients output

orangecontrib/survival_analysis/widgets/owranksurvivalfeatures.py
The widget now supports ranking survival features by multivariate log-rank test. If the feature is continuous, samples are split into groups by the median value.
=> [ENH] owranksurvivalfeatures: add log-rank scorer

.github/workflows/rebase.yml, orangecontrib/survival_analysis/__init__.py, orangecontrib/survival_analysis/tests/test_deprecation.py
=> CI - Automatic rebase
